var plants = 
[
    {
        name: "Black-eyed Susan",
        scientific_name: "Rudbeckia hirta",
        type: "wildflower",
        desc: "The beautiful yellow state flower of Maryland. Toxic to cats if eaten!",
        animals_attracted: ["rabbits", "butterflies"],
        animals_repelled: ["deer"],
        size: [1, 3],
        sun: ["full sun"],
        water: "Water frequently for first season",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Christmas Fern",
        scientific_name: "Polystichum acrostichoides",
        type: "fern",
        desc: "Common North American fern, prefers moist, shady habitats",
        animals_attracted: ["caterpillars", "gamebirds"],
        animals_repelled: ["rabbits", "deer"],
        size: [1, 2],
        sun: ["part sun"],
        water: "Water weekly until established",
        soiltype: "moist",
        display: true
    },
    {
        name: "Bee balm (Wild Bergamot)",//check
        scientific_name: "Monarda fistulosa",//check
        type: "wildflower",
        desc: "Common North American wildflower, attractive to pollinators",
        animals_attracted: ["bees", "butterflies", "hummingbirds"],//check
        animals_repelled: ["deer", "rabbits", "mosquitos"],
        size: [2, 4],//check
        sun: ["part sun", "full sun"],//check
        water: "Water regularly until established",
        soiltype: "well drained",//check
        display: true
    },
    {
        name: "Cardinal flower",
        scientific_name: "Lobelia cardinalis",
        type: "wildflower",
        desc: "Tall growing red flower preferring moist habitats",
        animals_attracted: ["hummingbirds", "butterflies"],
        animals_repelled: ["cats", "deer", "rabbits"],
        size: [2, 4],
        sun: ["part sun", "full sun"],
        water: "Water regularly for first year",
        soiltype: "moist",
        display: true
    },
    {
        name: "Goldenrod",
        scientific_name: "Solidago",
        type: "wildflower",
        desc: "Hardy yellow wildflower favoring meadows, prairies or savannas",
        animals_attracted: ["bees", "butterflies", "songbirds"],
        animals_repelled: [],
        size: [1, 3],
        sun: ["full sun"],
        water: "Water weekly until established",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Red Columbine",
        scientific_name: "Aquilegia canadensis, Aquilegia formosa",
        type: "wildflower",
        desc: "Moisture-loving wildflower that are highly deer resistant",
        animals_attracted: ["bees", "hummingbirds"],
        animals_repelled: ["deer"],
        size: [2, 3],
        sun: ["full sun", "part sun"],
        water: "Keep moist until established, then water weekly.",
        soiltype: "moist",
        display: true
    },
    {
        name: "Swamp milkweed",
        scientific_name: "Asclepias incarnata",
        type: "wildflower",
        desc: "Small shrub with fragrant pink flowers that attract monarch butterflies",
        animals_attracted: ["butterflies", "pollinators"],
        animals_repelled: ["cats"],
        size: [3, 6],
        sun: ["full sun"],
        water: "Water regularly for first year.",
        soiltype: "moist",
        display: true
    },
    {
        name: "Butterfly weed",
        scientific_name: "Asclepias tuberosa",
        type: "wildflower",
        desc: "Produces small yellow flowers that attract monarch butterflies",
        animals_attracted: ["butterflies", "pollinators"],
        animals_repelled: ["cats", "dogs", "deer", "rabbits"],
        size: [2, 3],
        sun: ["full sun"],
        water: "Water well for first year",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Flowering Dogwood",
        scientific_name: "Cornus florida",
        type: "tree",
        desc: "Small tree with sweet-smelling, beautiful white, pink, or red flowers, thriving best when planted in the shade of taller trees",
        animals_attracted: ["songbirds", "deer", "rabbits", "squirrels", "foxes"],        
        animals_repelled: [],
        size: [25, 35],
        sun: ["part sun", "full shade"],
        water: "Water weekly for the first two years",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Golden ragwort",
        scientific_name: "Packera aurea",
        type: "wildflower",
        desc: "Reliable, self sowing wildflower stays low and spreads out, making good ground cover in moist areas",
        animals_attracted: ["bees"],
        animals_repelled: ["deer", "rabbits", "most mammals"],
        size: [1, 2],
        sun: ["part sun"],
        water: "Water weekly",
        soiltype: "moist",
        display: true
    },
    {
        name: "Hollow joe-pye weed",
        scientific_name: "Eutrochium fistulosum",
        type: "shrub",
        desc: "Tall, bushy wildflower, very attractive to pollinators, needs consistently moist soil to thrive",
        animals_attracted: ["songbirds", "pollinators"],
        animals_repelled: ["deer", "rabbits"],
        size: [4, 7],
        sun: ["full sun", "part sun"],
        water: "Water every few days",
        soiltype: "moist",
        display: true
    },
    {
        name: "Dwarf Crested Iris",
        scientific_name: "Iris Cristata",
        type: "wildflower",
        desc: "Small, beautiful blue flowers. Drought tolerant once established!",
        animals_attracted: ["deer", "rabbits", "mice", "songbirds"],
        animals_repelled: [],
        size: [4, 6],
        sun: ["full sun", "part sun"],
        water: "Water weekly for first year",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Heartleaf Foamflower",
        scientific_name: "Tiarella Cordifolia",
        type: "wildflower",
        desc: "Compact plant produces feathery white-pink flowers. Slowly spreading ground cover.",
        animals_attracted: ["bees", "sparrows"],
        animals_repelled: ["deer"],
        size: [1, 2],
        sun: ["part sun", "full shade"],
        water: "Water weekly until established, and during dry periods",
        soiltype: "moist",
        display: true
    },
    {
        name: "Common Pawpaw",
        scientific_name: "Asmina Triloba",
        type: "tree",
        desc: "Deer-resistant tree produces a delicious, papaya like fruit in late summer/early fall.",
        animals_attracted: ["foxes", "squirrels", "racoons", "songbirds"],
        animals_repelled: ["deer"],
        size: [15, 20],
        sun: ["part sun"],
        water: "Water 2-3 times per week for the first few months",
        soiltype: "well drained",
        display: true
    },
    {
        name: "False Indigo",
        scientific_name: "Baptisia Australis",
        type: "bush",
        desc: "Large bushy perennial is deer resistant, attracts pollinators, and is easily grown",
        animals_attracted: ["moths", "bees"],
        animals_repelled: ["deer", "rabbits"],
        size: [3, 5],
        sun: ["part sun", "full shade"],
        water: "Water regularly for first year. Drought tolerant once established!",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Blue Wood Aster",
        scientific_name: "Symphyotrichum Cordifolium",
        type: "wildflower",
        desc: "Fall-blooming wildflower with blue, daisy-like flowers",
        animals_attracted: ["sparrows", "chipmunks", "bees", "butterflies"],
        animals_repelled: ["beetles"],
        size: [2, 3],
        sun: ["part sun", "full sun"],
        water: "Water regularly",
        soiltype: "moist",
        display: true
    },
    {
        name: "White Turtlehead",
        scientific_name: "Chelone Glabra",
        type: "wildflower",
        desc: "Fall-blooming wildflower with blue, daisy-like flowers",
        animals_attracted: ["pollinators"],
        animals_repelled: ["deer"],
        size: [1, 4],
        sun: ["part sun"],
        water: "Must remain moist -- water regularly, especially for the first year",
        soiltype: "moist",
        display: true
    },
    {
        name: "Common Milkweed",
        scientific_name: "Chelone Glabra",
        type: "shrub",
        desc: "Fast-growing and easy to establish, provides critical habitat for monarch butterflies",
        animals_attracted: ["monarch butterflies", "pollinators"],
        animals_repelled: ["most mammals"],
        size: [1, 4],
        sun: ["full sun"],
        water: "Water once a week until established",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Foxglove Beardtongue",
        scientific_name: "Penstemon Digitalis",
        type: "wildflower",
        desc: "Deer resistant, with white-pink flowers that are attractive to pollinators",
        animals_attracted: ["pollinators"],
        animals_repelled: ["deer"],
        size: [2, 3],
        sun: ["full sun"],
        water: "Water weekly in summer",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Golden Alexander",
        scientific_name: "Zizia Aurea",
        type: "shrub",
        desc: "Beautiful, easy to grow shrub is an important food source for many insects",
        animals_attracted: ["butterflies"],
        animals_repelled: ["most pests"],
        size: [1, 3],
        sun: ["full sun", "part sun"],
        water: "Water regularly in dry summer conditions",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Eastern Redbud",
        scientific_name: "Cercis Canadensis",
        type: "tree",
        desc: "Medium-size tree provides shade, beautiful pink blossoms in Spring, and homes for songbirds",
        animals_attracted: ["deer", "squirrels", "songbirds"],
        animals_repelled: [],
        size: [20, 30],
        sun: ["part sun", "full shade"],
        water: "Water regularly until established",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Chalkbark Maple",
        scientific_name: "Acer Leucoderme",
        type: "tree",
        desc: "Leaves turn a brilliant red color in the fall. Toxic to horses if they eat the leaves",
        animals_attracted: ["deer", "squirrels", "songbirds"],
        animals_repelled: ["horses"],
        size: [25, 30],
        sun: ["part sun", "full shade"],
        water: "Water regularly until established",
        soiltype: "well drained",
        display: true
    },
    {
        name: "Fringetree",
        scientific_name: "Chionanthus Virginicus",
        type: "tree",
        desc: "Compact native tree with fragrant, lace-like white flowers",
        animals_attracted: ["songbirds"],
        animals_repelled: ["deer"],
        size: [12, 20],
        sun: ["part sun", "full sun"],
        water: "Water once a week for the first few years",
        soiltype: "well drained",
        display: true
    },
    {
        name: "American Holly",
        scientific_name: "Ilex Opaca",
        type: "tree",
        desc: "Large, bushy, cone-shaped tree. Berries are pretty, but toxic to people and many animals if consumed",
        animals_attracted: ["songbirds"],
        animals_repelled: ["deer"],
        size: [40, 45],
        sun: ["part sun", "full sun"],
        water: "Water once a week for the first three months",
        soiltype: "well drained",
        display: true
    },
    {
        name: "St. John's Wort",
        scientific_name: "Hypericum Perforatum",
        type: "shrub",
        desc: "Medium sized shrub that likes sun, with cheerful yellow flowers in summer attracting pollinators.",
        animals_attracted: ["pollinators"],
        animals_repelled: ["most mammals"],
        size: [2, 4],
        sun: ["part sun", "full sun"],
        water: "Water once a week until established, and during dry summer conditions",
        soiltype: "moist",
        display: true
    },
    {
        name: "Eastern Bluestar",
        scientific_name: "Amsonia Tabernaemontana",
        type: "wildflower",
        desc: "Lovely blue star-shaped flowers attract pollinators.",
        animals_attracted: ["pollinators"],
        animals_repelled: ["deer", "rabbits"],
        size: [1, 3],
        sun: ["part sun", "full sun"],
        water: "Water once a week until established, and during dry summer conditions",
        soiltype: "moist",
        display: true
    },
    {
        name: "Creeping Phlox",
        scientific_name: "Phlox Stolonifera",
        type: "wildflower",
        desc: "Low-growing, mat-forming ground cover with beautiful flowers",
        animals_attracted: ["rabbits", "voles"],
        animals_repelled: ["deer"],
        size: [0, 1],
        sun: ["part sun", "full sun"],
        water: "Water once a week until established, in warm dry conditions",
        soiltype: "well drained",
        display: true
    }
];
